name: continuous integration

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout source files
        uses: actions/checkout@v3

      - name: Complete installation
        run: npm ci

      - name: Lint sources
        run: npx nx lint

      - name: Run unit tests
        run: npm nx test

      - name: Build project
        run: npm nx build
